### ISSUE TITLE
distDocker fails on osx Docker 2.1.0.1 (37199)

### ISSUE THREAD

**Issue by karbes** [augi/gradle-docker-java#8]
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':distDocker'
Caused by: java.lang.NullPointerException: Cannot get property 'empty' on null object
	at cz.augi.gradle.dockerjava.DockerExecutor.getDockerPlatform(DockerExecutor.groovy:49)
	at cz.augi.gradle.dockerjava.DockerExecutor$getDockerPlatform.call(Unknown Source)

The code tries to parse string start 'OSType:' from the 'docker info' output but seems new docker indents the output and adds space to it before like ' OSType: linux'.

Solution 1: 
Refactor DockerExecutor.getDockerPlatform() to use 'docker info --format {{.OSType}}'

Solution 2:
Refactor DockerExecutor.getDockerPlatform() to trim / parse with trim to get OSType

**Comment by augi** [comment]
Thank you for the fix!

Fixed in #9
